### ISSUE TITLE
"px-app.html" style module missing <dom-module id="px-app"> and <template> tags

### ISSUE THREAD

**Issue by GE-KevinOkamoto** [PredixDev/px-theme#1]
As per Polymer documentation:

https://www.polymer-project.org/1.0/docs/devguide/styling.html#style-modules

style modules should include <dom-module> and <template> tags.

As is, I'm getting the following error on importing:

`Could not find style data in module named px-app`

**Comment by nonmetalhail** [comment]
@carlosfhernandez Can you please create a rally story for this?

**Comment by mdwragg** [comment]
Fixed!
