### ISSUE TITLE
Consider removing px-iconography-design dependency

### ISSUE THREAD

**Issue by mdwragg** [PredixDev/px-theme#10]
As part of the redesign we may want to take the opportunity to drop font-awesome/px-iconography-design out of the themes. If people want icons we should be pushing them towards the new px-icon-set repo.

(cc/ @randyaskin @Menkhaus-ge @davidrleonard for thoughts)

**Comment by randyaskin** [comment]
Yes, I believe that's valid. It was only hanging around because of iconic buttons maybe? We always import px-icon-set everywhere that we're using the new ones (within components, in px-demo, etc).

**Comment by mdwragg** [comment]
👍 🐐
