### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by binbalenci** [PredixDev/px-theme#16]
Hi, can you provide a license for this so I can deploy it to webjars? Thanks!

**Comment by nonmetalhail** [comment]
Hi, This has a license; a GE Software Development License.

As this is part of the GE brand, it will **NOT** be opened sourced like other Predix Design System repos. To use the code in this repo, you will have to purchase Predix or otherwise work with GE procurement to obtain a license.

**Comment by binbalenci** [comment]
Hi @nonmetalhail,

Can we have a `license` in `bower.json` to link to the LICENSE that the project current has at least? 

I will make a pull request. Please check it.
