### ISSUE TITLE
Getting remote repo errors when calling npm install

### ISSUE THREAD

**Issue by mattymil** [PredixDev/px-theme#2]
When running 'npm i' for setting up examples and API, the action returns three errors. Output is as follows.
npm ERR! git clone --template=/Users/a218012662/.npm/_git-remotes/_templates --mirror git://github.com/PredixDev/webdriver-support.git /Users/a218012662/.npm/_git-remotes/git-github-com-PredixDev-webdriver-support-git-v2-2-1-d05455c7: Cloning into bare repository '/Users/a218012662/.npm/_git-remotes/git-github-com-PredixDev-webdriver-support-git-v2-2-1-d05455c7'...
npm ERR! git clone --template=/Users/a218012662/.npm/_git-remotes/_templates --mirror git://github.com/PredixDev/webdriver-support.git /Users/a218012662/.npm/_git-remotes/git-github-com-PredixDev-webdriver-support-git-v2-2-1-d05455c7: fatal: remote error: 
npm ERR! git clone --template=/Users/a218012662/.npm/_git-remotes/_templates --mirror git://github.com/PredixDev/webdriver-support.git /Users/a218012662/.npm/_git-remotes/git-github-com-PredixDev-webdriver-support-git-v2-2-1-d05455c7:   Repository not found.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/a218012662/.npm/_git-remotes/_templates --mirror git://github.com/PredixDev/webdriver-support.git /Users/a218012662/.npm/_git-remotes/git-github-com-PredixDev-webdriver-support-git-v2-2-1-d05455c7
npm ERR! Cloning into bare repository '/Users/a218012662/.npm/_git-remotes/git-github-com-PredixDev-webdriver-support-git-v2-2-1-d05455c7'...
npm ERR! fatal: remote error: 
npm ERR!   Repository not found.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/a218012662/workspace/px-theme/npm-debug.log

**Comment by mdwragg** [comment]
Good catch - we're looking at this right now...

**Comment by mdwragg** [comment]
OK, we've fixed it, could you please try again? Thanks.

(Thanks too @runn-vermel!)

**Comment by mattymil** [comment]
Yep that seems to work completed without error.
