### ISSUE TITLE
Unmet npm dependency 

### ISSUE THREAD

**Issue by mattymil** [PredixDev/px-theme#3]
Getting the following when running npm i

C17LT8GZF5V7:px-theme a218012662$ npm i
npm WARN prefer global grunt-cli@0.1.13 should be installed with -g
px-theme@0.6.4 /Users/a218012662/workspace/px-theme
├── UNMET PEER DEPENDENCY chai@2.x
├── UNMET PEER DEPENDENCY chai-as-promised@~4.3.0
└── grunt-cli@0.1.13  extraneous

npm WARN webdriver-support@2.2.1 requires a peer of chai@2.x but none was installed.
npm WARN webdriver-support@2.2.1 requires a peer of chai-as-promised@~4.3.0 but none was installed.

**Comment by mattymil** [comment]
Was able to manually install the dependencies which resolved the error. However, grunt complained about not having http-server installed. Installed this and now works completely.

**Comment by yashdoshi89** [comment]
@mattymil I do get these warnings, but everything works without having to install anything manually.
