### ISSUE TITLE
demo and api pages not displayed

### ISSUE THREAD

**Issue by mattymil** [PredixDev/px-theme#4]
After installing the demo and firing up the server via grunt depserve browsing to http://localhost:8080/ provides a view of the directory and files within, see attached screenshot. There is no demo location or API documentation as referenced in the README
![screen shot 2016-03-01 at 1 23 00 pm](https://cloud.githubusercontent.com/assets/416844/13437153/c15d42c2-dfb0-11e5-8ab0-dffb92e304c0.png)

**Comment by mdwragg** [comment]
Fixed by removing the misleading readme content - this component is a starting point for theming other Px components, hence it doesn't really 'demo' itself right now. In the future we will revisit this to flesh out demos and usage. Thanks for bringing this to our attention.
