### ISSUE TITLE
No 'px-theme.html' file

### ISSUE THREAD

**Issue by gedesigntech** [PredixDev/px-theme#9]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:

This seems to be just a minor doc correction:

The Getting Started section of README mentions including the following in the <head> of the consuming document:

`<link` rel="import" href="/bower_components/px-theme/px-theme.html"/>

But there is no 'px-theme.html' file.  Instead, there is 'px-theme-styles.html' .

So it looks like the <link> element above needs to be changed accordingly.

The same situation is in the README of the 'px-dark-theme' repo.

## Steps to reproduce the problem:

N/A

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

N/A
## Screenshots (_optional, but very helpful_):

N/A

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by randyaskin** [comment]
Updated.
